### ISSUE TITLE
Disable fast charging

### ISSUE THREAD

**Issue by deepu2** [SuryashankarDas/turbo-x3#1]
Hey, I've been using your kernel on darkness redefined, is there a way to disable fast charging?

**Comment by SuryashankarDas** [comment]
After my last commit many people are already complaining that it is taking too long to charge. So I am about to re add the fast charge. And as for your question, no it is not possible. Majority of the people like fast charge.

**Comment by SuryashankarDas** [comment]
If your issue is heating then just keep your device for 2-3 min unused after unplugged .
